# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmdb', '0002_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
