# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 23:41
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dmdb', '0003_blogentry_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='modification',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 12, 23, 41, 0, 173916, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
